services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
      - "3000:3000"

volumes:
  data:
